
    create table comment_likes (
        comment_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        primary key (id),
        unique (comment_id, user_id)
    );

    create table comments (
        author_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        post_id bigint not null,
        updated_at timestamp(6) not null,
        content TEXT not null,
        media_url varchar(255),
        primary key (id)
    );

    create table media (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        uploader_id bigint not null,
        file_name varchar(255) not null,
        media_type varchar(255) not null,
        url varchar(255) not null,
        size bigint,
        primary key (id)
    );

    create table notifications (
        is_read boolean not null,
        actor_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        post_id bigint,
        user_id bigint not null,
        message varchar(255) not null,
        type varchar(255) not null,
        primary key (id)
    );

    create table post_likes (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        post_id bigint not null,
        user_id bigint not null,
        primary key (id),
        unique (post_id, user_id)
    );

    create table posts (
        author_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        content TEXT not null,
        media_url varchar(255),
        title varchar(255) not null,
        primary key (id)
    );

    create table refresh_tokens (
        revoked boolean not null,
        created_at timestamp(6),
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        token varchar(255) not null unique,
        primary key (id)
    );

    create table reports (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        reporter_id bigint not null,
        target_comment_id bigint,
        target_post_id bigint,
        target_user_id bigint,
        note TEXT,
        reason TEXT not null,
        status varchar(255) not null,
        primary key (id)
    );

    create table subscriptions (
        created_at timestamp(6) not null,
        followed_id bigint not null,
        follower_id bigint not null,
        id bigint generated by default as identity,
        primary key (id),
        unique (follower_id, followed_id)
    );

    create table user_blocks (
        blocked_id bigint not null,
        blocker_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        primary key (id),
        unique (blocker_id, blocked_id)
    );

    create table user_credentials (
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint not null unique,
        password_hash varchar(255) not null,
        primary key (id)
    );

    create table user_profiles (
        id bigint generated by default as identity,
        user_id bigint not null unique,
        avatar_url varchar(255),
        bio varchar(255),
        display_name varchar(255),
        primary key (id)
    );

    create table users (
        is_banned boolean default false not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        public_id varchar(255) not null unique,
        role varchar(255) not null check (role in ('USER','ADMIN')),
        username varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists comment_likes 
       add constraint FK3wa5u7bs1p1o9hmavtgdgk1go 
       foreign key (comment_id) 
       references comments;

    alter table if exists comment_likes 
       add constraint FK6h3lbneryl5pyb9ykaju7werx 
       foreign key (user_id) 
       references users;

    alter table if exists comments 
       add constraint FKn2na60ukhs76ibtpt9burkm27 
       foreign key (author_id) 
       references users;

    alter table if exists comments 
       add constraint FKh4c7lvsc298whoyd4w9ta25cr 
       foreign key (post_id) 
       references posts;

    alter table if exists media 
       add constraint FKmypr9cjqwym6g8a40p9lxrjq8 
       foreign key (uploader_id) 
       references users;

    alter table if exists notifications 
       add constraint FK4sd9fik0uthbk6d9rsxco4uja 
       foreign key (actor_id) 
       references users;

    alter table if exists notifications 
       add constraint FK599539lym3mnkbqks0u806eac 
       foreign key (post_id) 
       references posts;

    alter table if exists notifications 
       add constraint FK9y21adhxn0ayjhfocscqox7bh 
       foreign key (user_id) 
       references users;

    alter table if exists post_likes 
       add constraint FKa5wxsgl4doibhbed9gm7ikie2 
       foreign key (post_id) 
       references posts;

    alter table if exists post_likes 
       add constraint FKkgau5n0nlewg6o9lr4yibqgxj 
       foreign key (user_id) 
       references users;

    alter table if exists posts 
       add constraint FK6xvn0811tkyo3nfjk2xvqx6ns 
       foreign key (author_id) 
       references users;

    alter table if exists refresh_tokens 
       add constraint FK1lih5y2npsf8u5o3vhdb9y0os 
       foreign key (user_id) 
       references users;

    alter table if exists reports 
       add constraint FKd3qiw2om5d2oh5xb7fbdcq225 
       foreign key (reporter_id) 
       references users;

    alter table if exists reports 
       add constraint FKomwg9agrme2bk1yhfkb2wowic 
       foreign key (target_comment_id) 
       references comments;

    alter table if exists reports 
       add constraint FKo1axek1cvpke5uwchcb0c1nlk 
       foreign key (target_post_id) 
       references posts;

    alter table if exists reports 
       add constraint FKpemp8lt5m0ujfywtgnuw4ypw9 
       foreign key (target_user_id) 
       references users;

    alter table if exists subscriptions 
       add constraint FK2gcr81tcjwoodd2d0bwungs43 
       foreign key (followed_id) 
       references users;

    alter table if exists subscriptions 
       add constraint FKke02anvdqljk55rmw29srne17 
       foreign key (follower_id) 
       references users;

    alter table if exists user_blocks 
       add constraint FK7k3mfgb03bnmwh81vqb1u5h80 
       foreign key (blocked_id) 
       references users;

    alter table if exists user_blocks 
       add constraint FKgvu85oyjrfafwttb7iphgmm0v 
       foreign key (blocker_id) 
       references users;

    alter table if exists user_credentials 
       add constraint FK98kxj78ausx1xo94eq4mkjm9q 
       foreign key (user_id) 
       references users;

    alter table if exists user_profiles 
       add constraint FKjcad5nfve11khsnpwj1mv8frj 
       foreign key (user_id) 
       references users;
